/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    competitions: Competition;
    feedback: Feedback;
    'membership-tiers': MembershipTier;
    'user-memberships': UserMembership;
    'leaderboard-entries': LeaderboardEntry;
    teams: Team;
    matches: Match;
    'ranking-history': RankingHistory;
    predictions: Prediction;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    competitions: CompetitionsSelect<false> | CompetitionsSelect<true>;
    feedback: FeedbackSelect<false> | FeedbackSelect<true>;
    'membership-tiers': MembershipTiersSelect<false> | MembershipTiersSelect<true>;
    'user-memberships': UserMembershipsSelect<false> | UserMembershipsSelect<true>;
    'leaderboard-entries': LeaderboardEntriesSelect<false> | LeaderboardEntriesSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    matches: MatchesSelect<false> | MatchesSelect<true>;
    'ranking-history': RankingHistorySelect<false> | RankingHistorySelect<true>;
    predictions: PredictionsSelect<false> | PredictionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('sk' | 'en') | ('sk' | 'en')[];
  globals: {};
  globalsSelect: {};
  locale: 'sk' | 'en';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * Meno, ktoré uvidia ostatní v rebríčkoch.
   */
  username: string;
  role: 'admin' | 'editor' | 'user';
  lastActivity?: string | null;
  isLifetime?: boolean | null;
  /**
   * Automaticky počítané systémom. Nemeňte manuálne.
   */
  stats?: {
    totalPoints?: number | null;
    /**
     * Aktuálne poradie v globálnom rebríčku.
     */
    globalRank?: number | null;
    /**
     * Poradie pri poslednom Snapshote (včera).
     */
    previousRank?: number | null;
    trend?: ('up' | 'down' | 'stable') | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competitions".
 */
export interface Competition {
  id: string;
  name: string;
  slug?: string | null;
  banner?: (number | null) | Media;
  status: 'upcoming' | 'active' | 'finished';
  startDate: string;
  endDate: string;
  description: string;
  /**
   * Ktoré úrovne členstva majú prístup do tejto súťaže?
   */
  requiredTiers: (number | MembershipTier)[];
  scoringRules: {
    exactScore: number;
    winnerOnly: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-tiers".
 */
export interface MembershipTier {
  id: number;
  name: string;
  /**
   * Vyššie číslo = vyššia úroveň oprávnení. Slúži na porovnávanie.
   */
  rank: number;
  price: number;
  features?:
    | {
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback".
 */
export interface Feedback {
  id: string;
  type: 'bug' | 'idea' | 'other';
  message: string;
  pageUrl?: string | null;
  user?: (string | null) | User;
  read?: boolean | null;
  status?: ('new' | 'in-progress' | 'resolved' | 'ignored') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-memberships".
 */
export interface UserMembership {
  id: number;
  user: string | User;
  tier: number | MembershipTier;
  status: 'active' | 'pending' | 'cancelled' | 'expired';
  validUntil?: string | null;
  billing?: {
    stripeSubscriptionId?: string | null;
    lastPaymentDate?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Cache pre body používateľov v súťažiach. Nemeniť manuálne!
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leaderboard-entries".
 */
export interface LeaderboardEntry {
  id: number;
  user: string | User;
  competition: string | Competition;
  /**
   * Aktuálny počet bodov. Prepočítava sa cez hooks pri vyhodnotení zápasu.
   */
  totalPoints?: number | null;
  /**
   * Aktuálny počet tipovaných zápasov. Prepočítava sa cez hooks pri vyhodnotení zápasu.
   */
  totalMatches?: number | null;
  exactGuesses?: number | null;
  correctTrends?: number | null;
  currentRank?: number | null;
  /**
   * Pozícia pri poslednom prepočte (včera/minulé kolo).
   */
  previousRank?: number | null;
  rankChange?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: number;
  name: string;
  /**
   * URL slug (napr. svk-team), voliteľné pre detail tímu.
   */
  slug?: string | null;
  /**
   * Trojmiestna skratka pre scoreboard (napr. SVK, KOS, SLO).
   */
  shortName: string;
  type: 'club' | 'national';
  /**
   * Určuje, odkiaľ tím pochádza (nie kde hrá). Boston Bruins = USA.
   */
  country: 'SVK' | 'CZE' | 'USA' | 'CAN';
  /**
   * Pomocné tagy pre ľahšie vyhľadávanie pri vytváraní zápasov.
   */
  leagueTags?: ('sk' | 'nhl' | 'cz' | 'iihf')[] | null;
  logo: number | Media;
  colors: {
    primary: string;
    secondary: string;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches".
 */
export interface Match {
  id: number;
  displayTitle?: string | null;
  competition: string | Competition;
  date: string;
  homeTeam: number | Team;
  awayTeam: number | Team;
  status: 'scheduled' | 'live' | 'finished' | 'cancelled';
  result?: {
    homeScore?: number | null;
    awayScore?: number | null;
    /**
     * Zvoľ, či zápas skončil po 60 minútach, v predĺžení alebo nájazdoch.
     */
    endingType: 'regular' | 'ot' | 'so';
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ranking-history".
 */
export interface RankingHistory {
  id: number;
  user: string | User;
  /**
   * Deň, ku ktorému sa viaže tento snapshot.
   */
  date: string;
  rank: number;
  points: number;
  competition?: (string | null) | Competition;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "predictions".
 */
export interface Prediction {
  id: number;
  user: string | User;
  match: number | Match;
  homeGoals: number;
  awayGoals: number;
  /**
   * Body pridelené po vyhodnotení.
   */
  points?: number | null;
  status?: ('pending' | 'evaluated' | 'void') | null;
  /**
   * Koľkokrát používateľ uložil/zmenil tento tip.
   */
  editCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'competitions';
        value: string | Competition;
      } | null)
    | ({
        relationTo: 'feedback';
        value: string | Feedback;
      } | null)
    | ({
        relationTo: 'membership-tiers';
        value: number | MembershipTier;
      } | null)
    | ({
        relationTo: 'user-memberships';
        value: number | UserMembership;
      } | null)
    | ({
        relationTo: 'leaderboard-entries';
        value: number | LeaderboardEntry;
      } | null)
    | ({
        relationTo: 'teams';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'matches';
        value: number | Match;
      } | null)
    | ({
        relationTo: 'ranking-history';
        value: number | RankingHistory;
      } | null)
    | ({
        relationTo: 'predictions';
        value: number | Prediction;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  id?: T;
  username?: T;
  role?: T;
  lastActivity?: T;
  isLifetime?: T;
  stats?:
    | T
    | {
        totalPoints?: T;
        globalRank?: T;
        previousRank?: T;
        trend?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competitions_select".
 */
export interface CompetitionsSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  slug?: T;
  banner?: T;
  status?: T;
  startDate?: T;
  endDate?: T;
  description?: T;
  requiredTiers?: T;
  scoringRules?:
    | T
    | {
        exactScore?: T;
        winnerOnly?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback_select".
 */
export interface FeedbackSelect<T extends boolean = true> {
  id?: T;
  type?: T;
  message?: T;
  pageUrl?: T;
  user?: T;
  read?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-tiers_select".
 */
export interface MembershipTiersSelect<T extends boolean = true> {
  name?: T;
  rank?: T;
  price?: T;
  features?:
    | T
    | {
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-memberships_select".
 */
export interface UserMembershipsSelect<T extends boolean = true> {
  user?: T;
  tier?: T;
  status?: T;
  validUntil?: T;
  billing?:
    | T
    | {
        stripeSubscriptionId?: T;
        lastPaymentDate?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leaderboard-entries_select".
 */
export interface LeaderboardEntriesSelect<T extends boolean = true> {
  user?: T;
  competition?: T;
  totalPoints?: T;
  totalMatches?: T;
  exactGuesses?: T;
  correctTrends?: T;
  currentRank?: T;
  previousRank?: T;
  rankChange?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  shortName?: T;
  type?: T;
  country?: T;
  leagueTags?: T;
  logo?: T;
  colors?:
    | T
    | {
        primary?: T;
        secondary?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches_select".
 */
export interface MatchesSelect<T extends boolean = true> {
  displayTitle?: T;
  competition?: T;
  date?: T;
  homeTeam?: T;
  awayTeam?: T;
  status?: T;
  result?:
    | T
    | {
        homeScore?: T;
        awayScore?: T;
        endingType?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ranking-history_select".
 */
export interface RankingHistorySelect<T extends boolean = true> {
  user?: T;
  date?: T;
  rank?: T;
  points?: T;
  competition?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "predictions_select".
 */
export interface PredictionsSelect<T extends boolean = true> {
  user?: T;
  match?: T;
  homeGoals?: T;
  awayGoals?: T;
  points?: T;
  status?: T;
  editCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}