/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    competitions: Competition;
    feedback: Feedback;
    'membership-tiers': MembershipTier;
    'user-memberships': UserMembership;
    'leaderboard-entries': LeaderboardEntry;
    'competition-snapshots': CompetitionSnapshot;
    teams: Team;
    matches: Match;
    predictions: Prediction;
    leagues: League;
    'mini-leagues': MiniLeague;
    'team-logos': TeamLogo;
    'rate-limits': RateLimit;
    announcements: Announcement;
    countries: Country;
    regions: Region;
    badges: Badge;
    'badge-media': BadgeMedia;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    competitions: CompetitionsSelect<false> | CompetitionsSelect<true>;
    feedback: FeedbackSelect<false> | FeedbackSelect<true>;
    'membership-tiers': MembershipTiersSelect<false> | MembershipTiersSelect<true>;
    'user-memberships': UserMembershipsSelect<false> | UserMembershipsSelect<true>;
    'leaderboard-entries': LeaderboardEntriesSelect<false> | LeaderboardEntriesSelect<true>;
    'competition-snapshots': CompetitionSnapshotsSelect<false> | CompetitionSnapshotsSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    matches: MatchesSelect<false> | MatchesSelect<true>;
    predictions: PredictionsSelect<false> | PredictionsSelect<true>;
    leagues: LeaguesSelect<false> | LeaguesSelect<true>;
    'mini-leagues': MiniLeaguesSelect<false> | MiniLeaguesSelect<true>;
    'team-logos': TeamLogosSelect<false> | TeamLogosSelect<true>;
    'rate-limits': RateLimitsSelect<false> | RateLimitsSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    countries: CountriesSelect<false> | CountriesSelect<true>;
    regions: RegionsSelect<false> | RegionsSelect<true>;
    badges: BadgesSelect<false> | BadgesSelect<true>;
    'badge-media': BadgeMediaSelect<false> | BadgeMediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('sk' | 'en' | 'cz') | ('sk' | 'en' | 'cz')[];
  globals: {
    'general-settings': GeneralSetting;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'general-settings': GeneralSettingsSelect<false> | GeneralSettingsSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: 'sk' | 'en' | 'cz';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      'update-matches': TaskUpdateMatches;
      'update-realtime-ranking': TaskUpdateRealtimeRanking;
      'sync-hockey-matches': TaskSyncHockeyMatches;
      'sync-future-matches': TaskSyncFutureMatches;
      'update-leaderboards': TaskUpdateLeaderboards;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * Meno, ktoré uvidia ostatní v rebríčkoch.
   */
  username: string;
  role: 'admin' | 'editor' | 'user';
  lastActivity?: string | null;
  preferredLanguage?: ('sk' | 'en' | 'cz') | null;
  /**
   * Informácie o predplatnom a úrovni prístupu
   */
  subscription: {
    plan: 'free' | 'pro' | 'vip';
    planType: 'seasonal' | 'lifetime';
    /**
     * Dátum prvej aktivácie predplatného
     */
    activeFrom?: string | null;
    /**
     * Dátum expirácie (pri Lifetime sa ignoruje)
     */
    activeUntil?: string | null;
  };
  hasSeenOnboarding?: boolean | null;
  gdprConsent: boolean;
  marketingConsent?: boolean | null;
  marketingConsentDate?: string | null;
  seenAnnouncements?:
    | {
        announcementId?: string | null;
        displayCount?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Automaticky počítané systémom. Nemeňte manuálne.
   */
  stats?: {
    /**
     * Aktuálne poradie v globálnom rebríčku.
     */
    globalRank?: number | null;
    /**
     * Poradie pri poslednom Snapshote (včera).
     */
    previousRank?: number | null;
    trend?: ('up' | 'down' | 'stable') | null;
    totalPredictions?: number | null;
    lifetimePoints?: number | null;
    lifetimePossiblePoints?: number | null;
    currentOvr?: number | null;
    maxOvrEver?: number | null;
  };
  /**
   * Nepovinné údaje o lokácii používateľa
   */
  location?: {
    country?: (number | null) | Country;
    /**
     * Zadajte názov vašej krajiny (ak nie je v zozname)
     */
    customCountry?: string | null;
    /**
     * Napr. Bratislavský, Jihomoravský, ...
     */
    region?: (number | null) | Region;
  };
  referralData?: {
    /**
     * Unikátny kód pre pozývanie nových používateľov.
     */
    referralCode?: string | null;
    /**
     * Používateľ, ktorý odporučil tohto člena.
     */
    referredBy?: (string | null) | User;
    stats?: {
      /**
       * Počet registrovaných cez tento kód.
       */
      totalRegistered?: number | null;
      /**
       * Počet platiacich (Pro/VIP) z registrovaných.
       */
      totalPaid?: number | null;
    };
  };
  /**
   * Vlastný dres používateľa
   */
  jersey?: {
    primaryColor?: string | null;
    secondaryColor?: string | null;
    pattern?: ('stripes' | 'bands' | 'plain' | 'chevrons' | 'hoops') | null;
    number?: string | null;
    style?: ('classic' | 'modern') | null;
  };
  /**
   * Získané odznaky používateľa.
   */
  badges?: (string | Badge)[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries".
 */
export interface Country {
  id: number;
  name: string;
  /**
   * Napr. SK, CZ
   */
  code: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions".
 */
export interface Region {
  id: number;
  name: string;
  country: number | Country;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "badges".
 */
export interface Badge {
  id: string;
  /**
   * Unikátny identifikátor pre systémové prideľovanie (napr. beta-tester, referral-1)
   */
  slug: string;
  name: string;
  /**
   * Podmienky získania odznaku
   */
  description?: string | null;
  iconType?: ('lucide' | 'upload') | null;
  /**
   * Názov ikonky z lucide-react
   */
  iconLucide?: string | null;
  iconMedia?: (string | null) | BadgeMedia;
  /**
   * Váha pre výpočet prestíže (1-10)
   */
  weight?: number | null;
  rarity?: ('bronze' | 'silver' | 'gold' | 'platinum') | null;
  /**
   * Určuje, či ho prideľuje systém automaticky
   */
  isAutomatic?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "badge-media".
 */
export interface BadgeMedia {
  id: string;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    badge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competitions".
 */
export interface Competition {
  id: string;
  name: string;
  slug?: string | null;
  banner?: (string | null) | Media;
  status: 'upcoming' | 'active' | 'finished';
  /**
   * Ak je zapnuté, používatelia sa môžu pridať do súťaže (aj keď je ešte len "upcoming").
   */
  isRegistrationOpen?: boolean | null;
  startDate: string;
  endDate: string;
  description: string;
  /**
   * Ktoré úrovne členstva majú prístup do tejto súťaže?
   */
  requiredTiers: (string | MembershipTier)[];
  totalPlayedMatches?: number | null;
  totalPossiblePoints?: number | null;
  /**
   * Hodina (0-23), kedy sa má prepočítať rebríček (default: 5:00).
   */
  recalculationHour?: number | null;
  /**
   * Externé ID súťaže z hokejovej API (ak existuje).
   */
  apiHockeyId?: string | null;
  /**
   * Sezóna v rámci hokejovej API (napr. 2026).
   */
  apiHockeySeason?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-tiers".
 */
export interface MembershipTier {
  id: string;
  name: string;
  /**
   * Vyššie číslo = vyššia úroveň oprávnení. Slúži na porovnávanie.
   */
  rank: number;
  price: number;
  features?:
    | {
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback".
 */
export interface Feedback {
  id: string;
  type: 'bug' | 'idea' | 'change_user_email_request' | 'custom_country_request' | 'other';
  message: string;
  pageUrl?: string | null;
  user?: (string | null) | User;
  read?: boolean | null;
  status?: ('new' | 'in-progress' | 'resolved' | 'ignored') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-memberships".
 */
export interface UserMembership {
  id: string;
  user: string | User;
  tier: string | MembershipTier;
  status: 'active' | 'pending' | 'cancelled' | 'expired';
  validUntil?: string | null;
  billing?: {
    stripeSubscriptionId?: string | null;
    lastPaymentDate?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Cache pre body používateľov v súťažiach. Nemeniť manuálne!
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leaderboard-entries".
 */
export interface LeaderboardEntry {
  id: string;
  user: string | User;
  competition: string | Competition;
  /**
   * Aktuálny počet bodov. Prepočítava sa cez hooks pri vyhodnotení zápasu.
   */
  totalPoints?: number | null;
  /**
   * Aktuálny počet tipovaných zápasov. Prepočítava sa cez hooks pri vyhodnotení zápasu.
   */
  totalMatches?: number | null;
  exactGuesses?: number | null;
  correctTrends?: number | null;
  correctDiffs?: number | null;
  wrongGuesses?: number | null;
  currentRank?: number | null;
  /**
   * Pozícia pri poslednom prepočte (včera/minulé kolo).
   */
  previousRank?: number | null;
  rankChange?: number | null;
  ovr?: number | null;
  /**
   * Posledná zvolená liga používateľa v tejto súťaži (pre perzistenciu prepínača).
   */
  activeLeague?: (string | null) | League;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leagues".
 */
export interface League {
  id: string;
  name: string;
  /**
   * Verejné ligy sa nepočítajú do limitov užívateľov.
   */
  type: 'private' | 'public';
  /**
   * Unikátny kód na pozývanie (napr. PUK-XYZ)
   */
  code?: string | null;
  owner: string | User;
  members: (string | User)[];
  /**
   * Hráči čakajúci na schválenie vstupu.
   */
  waitingList?: (string | User)[] | null;
  competition: string | Competition;
  /**
   * Maximálny počet členov. Pre Public ligy zvýšiť manuálne.
   */
  maxMembers: number;
  stats?: {
    averageScore?: number | null;
    totalScore?: number | null;
    memberCount?: number | null;
    rank?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * História bodov a poradia pre grafy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competition-snapshots".
 */
export interface CompetitionSnapshot {
  id: string;
  competition: string | Competition;
  user: string | User;
  rank: number;
  ovr: number;
  points: number;
  exactGuesses?: number | null;
  winnerDiff?: number | null;
  winner?: number | null;
  adjacent?: number | null;
  totalTips?: number | null;
  date: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: string;
  name: string;
  /**
   * URL slug (napr. svk-team), voliteľné pre detail tímu.
   */
  slug?: string | null;
  /**
   * Trojmiestna skratka pre scoreboard (napr. SVK, KOS, SLO).
   */
  shortName: string;
  type: 'club' | 'national';
  /**
   * Externé ID tímu z hokejovej API (ak existuje).
   */
  apiHockeyId?: string | null;
  /**
   * Určuje, odkiaľ tím pochádza (nie kde hrá). Boston Bruins = USA.
   */
  country?: ('SVK' | 'CZE' | 'USA' | 'CAN') | null;
  /**
   * Pomocné tagy pre ľahšie vyhľadávanie pri vytváraní zápasov.
   */
  leagueTags?: ('sk' | 'nhl' | 'cz' | 'iihf')[] | null;
  logo?: (string | null) | TeamLogo;
  colors: {
    primary: string;
    secondary: string;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-logos".
 */
export interface TeamLogo {
  id: string;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches".
 */
export interface Match {
  id: string;
  displayTitle?: string | null;
  competition: string | Competition;
  date: string;
  homeTeam: string | Team;
  awayTeam: string | Team;
  status: 'scheduled' | 'live' | 'finished' | 'cancelled';
  result: {
    /**
     * Vyber fázu pre zobrazenie špecifických polí
     */
    stage_type: 'regular_season' | 'group_phase' | 'playoffs' | 'pre_season';
    homeScore?: number | null;
    awayScore?: number | null;
    /**
     * Zvoľ, či zápas skončil po 60 minútach, v predĺžení alebo nájazdoch.
     */
    endingType?: ('regular' | 'ot' | 'so') | null;
    round_label?: string | null;
    round_order?: number | null;
    group_name?: string | null;
    series_game_number?: number | null;
    series_state?: string | null;
  };
  /**
   * Dátum a čas, kedy bol k tomuto zápasu prepočítaný rebríček. Ak je null, zápas čaká na spracovanie.
   */
  rankedAt?: string | null;
  /**
   * Externé ID zápasu z hokejovej API (ak existuje).
   */
  apiHockeyId?: string | null;
  /**
   * Pôvodný status zápasu z hokejovej API (napr. NS, P1, FT).
   */
  apiHockeyStatus?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "predictions".
 */
export interface Prediction {
  id: string;
  user: string | User;
  match: string | Match;
  homeGoals: number;
  awayGoals: number;
  /**
   * Body pridelené po vyhodnotení.
   */
  points?: number | null;
  status?: ('pending' | 'evaluated' | 'void') | null;
  /**
   * Koľkokrát používateľ uložil/zmenil tento tip.
   */
  editCount?: number | null;
  isExact?: boolean | null;
  isTrend?: boolean | null;
  isDiff?: boolean | null;
  isWrong?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mini-leagues".
 */
export interface MiniLeague {
  id: number;
  name: string;
  competition: string | Competition;
  owner: string | User;
  members?: (string | User)[] | null;
  /**
   * Kód, ktorý pošleš kamošom, aby sa pridali.
   */
  inviteCode?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate-limits".
 */
export interface RateLimit {
  id: number;
  ip: string;
  count: number;
  lastRequest: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: number;
  /**
   * Interný názov (nezobrazuje sa používateľovi)
   */
  name: string;
  isActive?: boolean | null;
  image?: (string | null) | Media;
  title: string;
  content: string;
  buttonText?: string | null;
  /**
   * Koľkokrát sa má oznam zobraziť jednému používateľovi (0 = nekonečno)
   */
  maxDisplaysPerUser?: number | null;
  targeting?: {
    /**
     * Minimálny počet bodov používateľa
     */
    minPoints?: number | null;
    /**
     * Maximálny počet bodov používateľa
     */
    maxPoints?: number | null;
    targetRoles?: ('admin' | 'editor' | 'user')[] | null;
  };
  icon?: ('bell' | 'trophy' | 'star' | 'gift' | 'alert') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          | 'inline'
          | 'update-matches'
          | 'update-realtime-ranking'
          | 'sync-hockey-matches'
          | 'sync-future-matches'
          | 'update-leaderboards';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?:
    | (
        | 'inline'
        | 'update-matches'
        | 'update-realtime-ranking'
        | 'sync-hockey-matches'
        | 'sync-future-matches'
        | 'update-leaderboards'
      )
    | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'competitions';
        value: string | Competition;
      } | null)
    | ({
        relationTo: 'feedback';
        value: string | Feedback;
      } | null)
    | ({
        relationTo: 'membership-tiers';
        value: string | MembershipTier;
      } | null)
    | ({
        relationTo: 'user-memberships';
        value: string | UserMembership;
      } | null)
    | ({
        relationTo: 'leaderboard-entries';
        value: string | LeaderboardEntry;
      } | null)
    | ({
        relationTo: 'competition-snapshots';
        value: string | CompetitionSnapshot;
      } | null)
    | ({
        relationTo: 'teams';
        value: string | Team;
      } | null)
    | ({
        relationTo: 'matches';
        value: string | Match;
      } | null)
    | ({
        relationTo: 'predictions';
        value: string | Prediction;
      } | null)
    | ({
        relationTo: 'leagues';
        value: string | League;
      } | null)
    | ({
        relationTo: 'mini-leagues';
        value: number | MiniLeague;
      } | null)
    | ({
        relationTo: 'team-logos';
        value: string | TeamLogo;
      } | null)
    | ({
        relationTo: 'rate-limits';
        value: number | RateLimit;
      } | null)
    | ({
        relationTo: 'announcements';
        value: number | Announcement;
      } | null)
    | ({
        relationTo: 'countries';
        value: number | Country;
      } | null)
    | ({
        relationTo: 'regions';
        value: number | Region;
      } | null)
    | ({
        relationTo: 'badges';
        value: string | Badge;
      } | null)
    | ({
        relationTo: 'badge-media';
        value: string | BadgeMedia;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  id?: T;
  username?: T;
  role?: T;
  lastActivity?: T;
  preferredLanguage?: T;
  subscription?:
    | T
    | {
        plan?: T;
        planType?: T;
        activeFrom?: T;
        activeUntil?: T;
      };
  hasSeenOnboarding?: T;
  gdprConsent?: T;
  marketingConsent?: T;
  marketingConsentDate?: T;
  seenAnnouncements?:
    | T
    | {
        announcementId?: T;
        displayCount?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        globalRank?: T;
        previousRank?: T;
        trend?: T;
        totalPredictions?: T;
        lifetimePoints?: T;
        lifetimePossiblePoints?: T;
        currentOvr?: T;
        maxOvrEver?: T;
      };
  location?:
    | T
    | {
        country?: T;
        customCountry?: T;
        region?: T;
      };
  referralData?:
    | T
    | {
        referralCode?: T;
        referredBy?: T;
        stats?:
          | T
          | {
              totalRegistered?: T;
              totalPaid?: T;
            };
      };
  jersey?:
    | T
    | {
        primaryColor?: T;
        secondaryColor?: T;
        pattern?: T;
        number?: T;
        style?: T;
      };
  badges?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  id?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competitions_select".
 */
export interface CompetitionsSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  slug?: T;
  banner?: T;
  status?: T;
  isRegistrationOpen?: T;
  startDate?: T;
  endDate?: T;
  description?: T;
  requiredTiers?: T;
  totalPlayedMatches?: T;
  totalPossiblePoints?: T;
  recalculationHour?: T;
  apiHockeyId?: T;
  apiHockeySeason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback_select".
 */
export interface FeedbackSelect<T extends boolean = true> {
  id?: T;
  type?: T;
  message?: T;
  pageUrl?: T;
  user?: T;
  read?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-tiers_select".
 */
export interface MembershipTiersSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  rank?: T;
  price?: T;
  features?:
    | T
    | {
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-memberships_select".
 */
export interface UserMembershipsSelect<T extends boolean = true> {
  id?: T;
  user?: T;
  tier?: T;
  status?: T;
  validUntil?: T;
  billing?:
    | T
    | {
        stripeSubscriptionId?: T;
        lastPaymentDate?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leaderboard-entries_select".
 */
export interface LeaderboardEntriesSelect<T extends boolean = true> {
  id?: T;
  user?: T;
  competition?: T;
  totalPoints?: T;
  totalMatches?: T;
  exactGuesses?: T;
  correctTrends?: T;
  correctDiffs?: T;
  wrongGuesses?: T;
  currentRank?: T;
  previousRank?: T;
  rankChange?: T;
  ovr?: T;
  activeLeague?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competition-snapshots_select".
 */
export interface CompetitionSnapshotsSelect<T extends boolean = true> {
  id?: T;
  competition?: T;
  user?: T;
  rank?: T;
  ovr?: T;
  points?: T;
  exactGuesses?: T;
  winnerDiff?: T;
  winner?: T;
  adjacent?: T;
  totalTips?: T;
  date?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  slug?: T;
  shortName?: T;
  type?: T;
  apiHockeyId?: T;
  country?: T;
  leagueTags?: T;
  logo?: T;
  colors?:
    | T
    | {
        primary?: T;
        secondary?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches_select".
 */
export interface MatchesSelect<T extends boolean = true> {
  id?: T;
  displayTitle?: T;
  competition?: T;
  date?: T;
  homeTeam?: T;
  awayTeam?: T;
  status?: T;
  result?:
    | T
    | {
        stage_type?: T;
        homeScore?: T;
        awayScore?: T;
        endingType?: T;
        round_label?: T;
        round_order?: T;
        group_name?: T;
        series_game_number?: T;
        series_state?: T;
      };
  rankedAt?: T;
  apiHockeyId?: T;
  apiHockeyStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "predictions_select".
 */
export interface PredictionsSelect<T extends boolean = true> {
  id?: T;
  user?: T;
  match?: T;
  homeGoals?: T;
  awayGoals?: T;
  points?: T;
  status?: T;
  editCount?: T;
  isExact?: T;
  isTrend?: T;
  isDiff?: T;
  isWrong?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leagues_select".
 */
export interface LeaguesSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  type?: T;
  code?: T;
  owner?: T;
  members?: T;
  waitingList?: T;
  competition?: T;
  maxMembers?: T;
  stats?:
    | T
    | {
        averageScore?: T;
        totalScore?: T;
        memberCount?: T;
        rank?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mini-leagues_select".
 */
export interface MiniLeaguesSelect<T extends boolean = true> {
  name?: T;
  competition?: T;
  owner?: T;
  members?: T;
  inviteCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-logos_select".
 */
export interface TeamLogosSelect<T extends boolean = true> {
  id?: T;
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate-limits_select".
 */
export interface RateLimitsSelect<T extends boolean = true> {
  ip?: T;
  count?: T;
  lastRequest?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  name?: T;
  isActive?: T;
  image?: T;
  title?: T;
  content?: T;
  buttonText?: T;
  maxDisplaysPerUser?: T;
  targeting?:
    | T
    | {
        minPoints?: T;
        maxPoints?: T;
        targetRoles?: T;
      };
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries_select".
 */
export interface CountriesSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions_select".
 */
export interface RegionsSelect<T extends boolean = true> {
  name?: T;
  country?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "badges_select".
 */
export interface BadgesSelect<T extends boolean = true> {
  id?: T;
  slug?: T;
  name?: T;
  description?: T;
  iconType?: T;
  iconLucide?: T;
  iconMedia?: T;
  weight?: T;
  rarity?: T;
  isAutomatic?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "badge-media_select".
 */
export interface BadgeMediaSelect<T extends boolean = true> {
  id?: T;
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        badge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "general-settings".
 */
export interface GeneralSetting {
  id: number;
  seo?: {
    /**
     * Ak nevyplníš, použije sa globálny titulok.
     */
    title?: string | null;
    /**
     * Ak nevyplníš, použije sa globálny popis.
     */
    description?: string | null;
    image?: (string | null) | Media;
  };
  gdpr: {
    content: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  cronSettings?: {
    /**
     * Ak je zapnuté, systém bude automaticky prepínať naplánované zápasy do stavu LIVE po ich začatí.
     */
    updateMatchesEnabled?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "general-settings_select".
 */
export interface GeneralSettingsSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  gdpr?:
    | T
    | {
        content?: T;
      };
  cronSettings?:
    | T
    | {
        updateMatchesEnabled?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskUpdate-matches".
 */
export interface TaskUpdateMatches {
  input: {
    manual?: boolean | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskUpdate-realtime-ranking".
 */
export interface TaskUpdateRealtimeRanking {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSync-hockey-matches".
 */
export interface TaskSyncHockeyMatches {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSync-future-matches".
 */
export interface TaskSyncFutureMatches {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskUpdate-leaderboards".
 */
export interface TaskUpdateLeaderboards {
  input: {
    force?: boolean | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}